---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openldap-credentials
  namespace: openldap
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgBdlvY1/cHi+bwqpueJXpl7wcA27vIzo8N6NyLr3jpb3iDWwvHXEw/566rKeZCwG7fItd7NqLP5UssYNlxjaFQsfNsTSaz8+oTBq26pFLyKaA5UJSGfONaELGn7PKQhJi4MHDSGXFqMbr8Mofr1/XDuu6EXB8GiOrQaQxRRwbh+2YDg5VGr6uE46YGVDqjUjGh5if1yV0Iz6qHW4g7MrsSm4wEh1LeEq7f+mxDAgvAn0xGVv3ENtNucpTaRaPU9BSxlnzfF2AG9bdKm98GN1vK8Sh6ADQVFmFpFo2XOjzAJOLRTojeFsForXPtEmtwTwosM+rpt5lUg0YnxTVIV4GeVi/y2zs6GjB4dcfWtZHKUkSeHO9sxTBwmU1zrUmjmnezPDF7KdrqYiZs6Of5NO2Xs7eZT35J5SNLJefZ9Bl8yyiUojoUdXbsIvvEuqTxg594gAZudJngBPLY9k5rHCTzXYbXYkNf2zGPSDXHsJGqsU7fYzX3VowPxpDUQNFx+wTHsppEAtCXQWKYJmNlZRcdlIMkhmaXnuR8YvjAIL1eOEBOXArG41Dz3DksnCphx9DVcfUaKUQKsuwl/xsvHHJTv5rzb/R4MDFEr7BMNzxw4BhLcIHkzK35qVTv1zsyDvz1VP7sPSnCDxuHLW/mkjvAasIKFZ05w0zkEJgRiA/VXfRCa1iMU+/ZpHbIHZ/pVJjO8PpTV/WVrKkpOxAaWR1oKbsvHVHklNtk=
    LDAP_CONFIG_PASSWORD: AgB3sqgvL5A3NuXb02XTHx2YxEKIWpNoLlr2Uq4WIsbZ1UUGPl9nitFQUD8aKFqW6qd9ILzpMg5x/CXSgRI+KMbTfDg5NtStK/9ReNBlS1VzS3WQPMT/CrsR7A7CT1j2l5oZm+P4/6xBp+lQjhMLa89A+g+G3jlpKoyqsG46LB9RIO9Z6Zq2KTc0/S/xz/OvJDu6xwbj/4Evo7oSyUT0M7My7Y8UTsNP76B8US4co8Man/8c7r+H7wKluVOrgtc3HIAAOavof79FwtxKwABx7AgvJ9442tsm6FWvVs80d+DyY4ur0dZhx/pVfhoiTREGluxHyF56yl+ZiPE1kt1auVelMmZTVi6XzB4slnMs30+XZ5us2zvqMdRW9gp++o3o1b3kIr5ndGGf3kdunvZAmjDK/zs6XzJtslBNT9Rn3SloRUWgBFRi1oUklz9/KM3m/DjU9xa5Lv9ZLToKJ8TZ9+6hjP/sHsmA+kKz/Nv6M3Kz+RezMslhHeLiK7Tatoo9hk/3nhMSIuClIhuJvR8xfotwemIIzOLrP7s/sveqnaiOTqPO6+NXt3zstzy3YMYXxKirzsZajSGd0UqCaq3jcNcEi470L0gJFniC0dFcSKVYhVW7sdINJLv0aYzENWkFFWr0Z7MWnL5MNTCGBYfDPCVgbRB/VpPsslY4tkIhS69ea5qYSt4EC3wZnZl1dAy9AySF+8FHxD86YSGeomkl/3s98+PCl4S0/PU=
  template:
    metadata:
      name: openldap-credentials
      namespace: openldap
