---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgA1FaMAF+lQaNwvMZdEjTG7gZhpLTgDR78IMtVMb8+OwFo4KE8NPXID86FDlcSiyfa8b9pHQSXqPtUl2oT44PqLPHFYt4PEJz2XInD4EB/yVr2BPNfmhQEhvwcoHHykvw+LLQrP1kHzqGP0miPDYaS8V8XpsrNQfVnRTsJwu9VRzsM0kCRpNHFMrQ774fTJSBxlKMPLdPbKnGgRx5RxEvCLoqn8UFIND83lLYSX4gCkjor0ArvC21yvcwPzeWPY9uivv1aBknPL75kitHIMx5Jld2KPK2+oLWWtZlQyXs5ONCJWidTVR5+ynJwwAa3h90abC2QuDDSI3HfeKWlzvsiFbCUU0JfY6QNsscIKnUlqmzvVwSvSOLVbo1Flq3hbKP9apKtjTOv20vwgSf4OpPR3+cGat3ZMIqppy75oY5CLQIF1TsurKlyOj0W40KZiMNud2XLeodB48IrMohmx0arDTy6dgVyiITe45jJsk1NRoGeZA7gDE2QETD6Ap9VU6+lhhjCSS0k5ySmsxNyDsQc2moOVcJkHJly3YjRFli8e7PxgJBMp7+L+EMN8L22JL12dMhrM7+FFb0IOevW5Ua4esq5IVsw5lbTofsFhnsV8OAWggofgM8VTYa72vqUDADJCy6i2OdGXgb9qGS10/SyZiprrLsCX4ysUfVItnLXoYj87OfcCdo4H106VoYBeBIi0dJwtwN6R6/YdnhjG+8M2tX0Lgmo7eolC0wDMg2NPWA==
    rootUser: AgBOboG27ONfM+TjCDQ7p8g/T0kV1cWStDhPOwymsPE3m+shWfrS9yvu9xEf+5dCXCfPxfS/rIOx1G2ttT0NrYdhHuL0DYgt6o8b6h8AjH3kMTpWL/gR0t74jIt4FVShN83yI64O6RJj9gIucWQoC+xTNXrZrGc14odp6ttov4VHPOslDmdT208wet/Flvp+/pVR8YUDhR7wgsSe0Wh98/X4Raj89dMH4zSSNSwZeRnESr3pL3pL0Gzu7uJWXwS+T+E+4HUp3u/qTiq67ViygIG4W0bwTcAtKZB/Qw7F4db9tCAq/bvhlGIYCM6BbuJuDu+QbMw5X5fV9cWql/ts/eM9vYdDimsOx2nS2xjwlqMZgmswlB3SCvuzkGivKyQ5UIwfDjqviZL4YnH2NTg2nYF/NvEMiM8UwdbeRGpjXmSNMDRXdLhS0B6IQf/A0PDbvVwu7+1tgqrM3ZLVrKVOFz1S/bFQMiwy8rHTyVWZe+ERiBPQVLMDfzg4X0gWsbfytGPItsayoErpe5to4S2SAtqembBf+TiRkC3K0ix2uEiR/0WOoua9TzHPjupe2HvsvKpROoJY4ZXOYiI27LitAVmZnfyBQPdbf+kQY71nUUXHnT5RBujHA1RyMM8wE+B+eKhGpt+7Roo8/ZxEcYfvtZ+r7L6Jrqbtg0ptRn4+njII5PGe36kUuAvpwtKa3IXOQjFdIYu3Jw==
  template:
    metadata:
      name: minio-root-credentials
      namespace: minio
