---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgBGxro3Y/73ERr7OhkCuC/CYR4NlNcRp//kyKwBYNw0fSXkMtsJB+4s0B/xMqlg/zsWMueJX0N6OSTBviY88iBNEKg3BlIYV0pNrkzXtHMBq54Hw+HxossPgw8/06ZX9MHvSDl5KuueslwTuRKZ7TYtx5WBVg0mFbCk3yysmKKYIks5swpsONCEOJ+Q96QGQYTelZbV/sfqA2Wh9H3gRDcnGTSVBi+AN76npIpW64iOai7gW0TfQJoS9AYLgcHbp17U/7O7HEs6v4J1Iwz3w6p9kcERE24RmC9KBhtWHpwdfXa/avNY1YadcloDExglQb71n7cMmoXC5kF08FJ3DZL2SKbzTfuvcJRbdac5mvfhsfWwwDZjrV7yPd61AYQEawEqJ+XwwPkJB8KFySObicj5pFzapA0MagPqoc6FNoS2It9pMfnxk8Y/xHXdFjgbX+dDS94G1dIkAWGuts3DMtVt4UxvtjPNqd+hetZ529F9hQGcAcui/dSzx0gy8GCC/P7UrSvFFacqdukm+rOXvcTvO7ou/TranwUPLrJm2vWfGcXAREJRPb+d21h3TwIC11PF3B9V2Xw6SOT6I+2Smjb8YOuOZrfktm+DM1fEdOlMUNK1+QzMm4FuapyiI1ZmfAxAGEoWwHlqgg5jm1j97vXGdLuatqaKTCK4uY8y6BMjsQNlBGl4wjnobz8zjbAognJnd6ckIYemPfmvaLDo7yRUS9uV06Pl1Ww=
    postgres-password: AgAobhFGsmXWLQCXi9ayYUcT/6YWPwKUTF+PmG5uJPq+SJadGGudjtUcvIHB2ou6SvPzHexFxNHF40oJLI17eBLyFsudoE4W40nPdRRHw2p8YIM2+Ivx7aE+CEfPG0pggYZQxCe/JHzpi+NuHNwbb5Qzjfkq0yl30Fktn0wfquIaE2vQ2/LqN3kpJJOpxfNeCTEesspql3QkrCCQvyak09HrAAi5TQeMDmBf/mt24ZuqeQWrjyYhgKpcSX2I0QuqaUFl0qG3ojD/kjuvud/ZMSCdupCLvEfTmOVYW+jsjYvVBgCd+K7wpB/J29H48GEHhFBdiJRWsYePdwQ5M4EUyiwgh1EqzP8x+xO4cN0M1AzO1FrkbVMHOd9+KovVzQiyoQz5SzKFUg5voW07i6PK9LmCM6bSoh+lpB+GADr8VMFvHTDVY4MnOsvZQ03oz+oSHSPL9FlSYqbRBs7pRXC31KWX0hZs1O8cmMZvtaIRX6R1v483YO1Dg9WdUnawDHm+D7A7nb8B0hnYUhML0GVA9wghfP/Kp0GdnfdxLXUxHipmdM39z5BkAfnDo1yo9yq7UyAoEkTueefcoB1h5WmGePjdwyjcxc/QOahF5c3QHDgThd4WKdFfcW0gNjlDkbk3TquEw04w3koHPqpr5Tm+Kp7cCEHX/+cRglIVD3wLBQjYT5OI3NOtgd9LBR9pe3mZbEL4qNo7hQYafd3kgVXyde5Gm/7Jc5MUNSA=
  template:
    metadata:
      name: keycloak-postgresql-credentials
      namespace: keycloak
