---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgBQaywuUonSlEtPsG0wGmaxUJbe9i4eapKMWG0086CZ/5d6NkDamVhJNgu7d/VuWPaxvrhYgH5bB+6YerrGrwNrZdEicnM5lXPiKQFBTZVVC7U9nvAy/WZHv1NWw6QPVsuzl4vcgd3LcREjq8fEdnGWlFfuT/D5HkhiOpYQ5xZ9lF5o2QSJnqBxS3IlmpPm+zq99rEKJor0MCwISFj8KvgS911AdshngZPLVJH3w9VnXILi6O5p33MlLJGVTYDwOcB69s21oJobKcrJ+pE+48r1TeiMbwu8U9MLOIofeytPrYfVecqqZBI7Q24Oq394kcmTvU7p74zj9oCr3uMuEk3UdXi5pG+YKn6qyNyEGDqgXHUIxqtMZ5pGCNGomR6pdraz4qnq9LRaTs7u1s4/VY3WWy/iDXwPxEG2AuxcjaY2/oNtaADldzoI5wgqo0pR4k8uMHx1AcvWBmzBpQHJitLFmWSfKxzn38wJ6ZMou5TxuN6WCmys281i8jCmMQuHxN5Vq9BZBgw4t4hVcEeOEvMRnBU1DgsswpPUprfYLiDOaMH3MrH/ctZUHn0TDflLEGkogI+WQG5A+MK2LlyHmhf5aN1yCxzGJDf3PKWbpflsplqwqP6xYVjvT42v7AVXR8LDb7Q7NMDkpBI3KTPOICKGleDwN9xARdfMGkFJ/NMTqwZ+UeJoC4wU0KdMCGOGAt3oBORhkcTfJ1XGaQH0+3oAF640ryBTKM0=
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: keycloak
