---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBCsdFLIZdmqRswVVMkCJnSnwmT3CO4ZuSFIss7zyGfrQNK8rxwuWr36ysrWO/Bfjhx/UCuE8sYGExa+oImfs2c+Wn/WTJof0rp5xpYqS7VNCEtilfKZ/gw5CFhC2ciEX3KUXBb9A8bPmSOC3gRb978IfYU0wCFSpp2/fp+SELFc99DY9KaEsLaC+QT3Cwyo0bNrKgMg2nAPI0siu6revQWjE/vpcwTqAUXLzz4pFzfU7QyMuTpQjPNQukslysSez+Uo0/3+VGUIQeh8PjRA1WG8SmkIv+1G5ot/lWghJAg3AR7f0TWQXzam98J/7TZaNpczYMwyvRHQmT7+y6nMxN0600OVyySGt+3FzmHjXAMofzAEXWhExX1HY9MhH9/gKniyGPc3W+v4aqkw7GtgLa21W4Qlxf63t9oY9QCoZjQX4dFlIkXzZALqUyeMi2XGSCLo1jno1VpmrjLGBjyo9mplsl13EQy7H9rMu0+jb96jGZSWx3FPeb2ecuGQ9G/90/LNJwCheCbrNKQLCBBko9uChr0UwVGhhOfhX4dKEQQ6bsbiGwcI67zMhy45SKxPKwxohXlj/Y+opDk58rEEYkpw3HFW7EX/WllZb0Pl+joIs8oGX+Ho0KTY/LUXjBjDBH7p52IEpCMy+KufoexX1Twd+hJF9ui+0El1Wtsyn634T20IHgfW1hs+keLR0gboUt6tANWFWfGFPsISkz4NIEx8+dEkqvOLV06LgpeA35WkQ==
    admin-user: AgCMkGwBUVRK+uqIvJYNxbsiJbHK/+FrYzC2xoHJEuYLPlaRsyfKOOQOkRJdQTmc/t7GYj0Kl/ONIsUETaDOnD7aUgi6Ihw7M/3ASsHFeJsv1R1gjoZJGzMGLEWlyl2xfn8uzVjPdMemhLzOE/AhRa1zPry85SI3U6P80oiKrSEF3fCQy4eFsiqVRmhv57GoFgdx44fcKye+Ef43k0RxHgO4p+HDJ1iSZef8GGKzHo6dfc8oSwWPYApNEyBRgQDOTzZOCQnoJTjcJ0DNg06s2OM8anPPtL4PawISDQe4quokfZOyXm3NrT3ptnNBNt5XMT8aTyXHSTvfr0IuAVXpVrUsMWFPeiK2+oaBf2be5tyTXl8rDMSYHDUEFYU7fkl63uB6Eora1yrEDT/zDwjCG3nrMaeS8GUlDdDocHfMDzctIWGoIV3U4z8eigAFpK0vtZnsGbV1S6lb1VlP0VBlnjVjxD94ZGjJ1IO8WG2p0YblqNvMD1AhpsaZxKKoXbdC41KVFzf/GxK0uX9vPitG/K3El92dvLdciMRZ24rDdn+QS3vPubAXg5W426BYsxnwQ1NVdKryX64PNYIzEeiiYw/W3pjUcvgyx3pHqiiU+jNo0Ii9l2AqsciPKTv5hZjfT3JlsEKOOcs71WVXkB5Hy7FNBGJaGjlOCx2uPkmbuuHJKmLBb1+J2njbet1aFWTzmB1V0tEfFg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
