---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAK2UD0ar4ptn+FT5fYaBpPgkgmCjNGl7wI0zuDyKRmiGNVVSfvzNdBvMdAoOkdtDuqJOjHr9YvqnGwGmp0ISKfFy4IFq9cN76G2f0pH3tNLjKjyo/iE4KDSN13HxZSkq8KtsiKAOm/1XbOIWJRhIZXM4wubc+UNN5BSlECYVPgFGci2UmjMNVN543jvcu1AAhH8s3tQstV+dEielkkHnN1FPd5fYJ7tDjbHgB98HhA2KYdqEwjx3wmVIxMkLAWIx/Rh55FKwnu/7grP/bbxq0a0K5B9hi0pfr2LmwvUm/9ZpzHbCH7NAeI0uybX4HfRxCnLb4x/cqL/x8Rs56V/LMxDjV+TKXs43nFvyF1kvEC9p4eYTGxlpQKJmZvQUV1YayFtOFevmPVKJwD0lSJm7YvXHGhm1mSX730n7K9TSIgmzrfBlK5VGT+/qz0CSUW6+aIie00iVXaswvonnVRoNeOZKKUhyg6R15lmHHnufoFcg0F3y1yVekcc5Lxy+jAJhBKnEBiTGJvX4BYqM3xPdYtZV336KSZ22o7qBbN4sJS7M2v2+Ignb85UZJfc4i4+rmoP97QtFlEreDIN+Q24KLEDzztMcyyipALxxGCNv7P0DvlJhzjBvvlDrPBrXN71jeisCpzrq91i9/n7HfDBZC43YN8LaRpCBwtTMO3ldC8QSp1SBMwKT23xuC+goN3ugmpGe76WyKxQxRr2BASLq28SpRgyPyeSUk=
  template:
    metadata:
      name: grafana-oidc-credentials
      namespace: monitoring
